### ISSUE TITLE
无法保存配置

### ISSUE THREAD

**Issue by zangxx66** [pcrbot/HosBotManagerWeb#2]
按群组关掉服务后，刷新页面又复原了
./templates/group_services.html第55行后没有调用save()函数保存更改

**Comment by LQBing** [comment]
页面下面有个保存按钮，要点保存才能保存设置。

**Comment by LQBing** [comment]
> 按群组关掉服务后，刷新页面又复原了
> ./templates/group_services.html第55行后没有调用save()函数保存更改

页面下面有个“保存”按钮，要点“保存”按钮才能保存设置。你确定你点了“保存”按钮？

**Comment by LQBing** [comment]
> 按群组关掉服务后，刷新页面又复原了
> ./templates/group_services.html第55行后没有调用save()函数保存更改

还有问题吗？没有的话，我关掉咯？
