### ISSUE TITLE
于缝合的yobot会冲突

### ISSUE THREAD

**Issue by sugar-zero** [pcrbot/HosBotManagerWeb#3]
于缝合在hoshino内的yobot模组的web功能会冲突
虽然能用同一个端口进行访问，但无法登陆，点击登陆后会服务器错误
![image](https://user-images.githubusercontent.com/32754222/89904896-0dfb7600-dc1c-11ea-9721-fa0642222a9d.png)
另外提一下，因为yobot的域名都是单独设置的不是读的配置然后使用反代进行的web访问，而bot管理读的配置所以“bot设置”回复的是0.0.0.0:xxxx
怀疑是一个定向的问题

**Comment by sugar-zero** [comment]
另外很多资源样式都无法加载，看了配置中资源用的路径是/，与yobot共存时路径/变成了从yobot下去读取（就还是定向问题）
![image](https://user-images.githubusercontent.com/32754222/89905389-b4477b80-dc1c-11ea-8d1d-a53bcb0f499e.png)

**Comment by sugar-zero** [comment]
另外提一下，与yobot共存时资源无法读取，因为重定向的问题，资源路径/会默认在yobot下
![image](https://user-images.githubusercontent.com/32754222/89905597-f5d82680-dc1c-11ea-8d44-c584ba3fb097.png)

**Comment by LQBing** [comment]
sorry,这是引用相对路径的问题，是我这边漏提交代码了。
刚刚提交了，你试试看？

**Comment by LQBing** [comment]
> 于缝合在hoshino内的yobot模组的web功能会冲突
> 虽然能用同一个端口进行访问，但无法登陆，点击登陆后会服务器错误
> ![image](https://user-images.githubusercontent.com/32754222/89904896-0dfb7600-dc1c-11ea-9721-fa0642222a9d.png)
> 另外提一下，因为yobot的域名都是单独设置的不是读的配置然后使用反代进行的web访问，而bot管理读的配置所以“bot设置”回复的是0.0.0.0:xxxx
> 怀疑是一个定向的问题

这个问题的话，README.MD里有

如果不想用环境变量，则可以修改hoshino/modules/bot_manager_web/reply.py中的PUBLIC_ADDRESS后面值修改成你想要的url。

**Comment by LQBing** [comment]
> 另外提一下，与yobot共存时资源无法读取，因为重定向的问题，资源路径/会默认在yobot下
> ![image](https://user-images.githubusercontent.com/32754222/89905597-f5d82680-dc1c-11ea-8d44-c584ba3fb097.png)

sorry,这是引用相对路径的问题，是我这边漏提交代码了。
刚刚提交了，你试试看？

**Comment by sugar-zero** [comment]
> > 于其中在hoshino内的yobot模组的网络功能会冲突
> > 虽然能用同一个端口进行访问，但无法登陆，点击登陆后会服务器错误
> > 另外提一下，因为yobot的域名都是单独设置的不是读的配置然后使用反代进行的网络访问，而机器人管理读的配置因此“ bot设置”回复的是0.0.0.0:xxxx 
> > 怀疑是一个定向的问题
> > ![图片](https://user-images.githubusercontent.com/32754222/89904896-0dfb7600-dc1c-11ea-9721-fa0642222a9d.png)
> 
> 这个问题的话，README.MD里有
> 
> 如果不想用环境变量，则可以修改hoshino / modules / bot_manager_web / reply.py中的PUBLIC_ADDRESS后面的值修改成你想要的网址。

我试过更改成我想要的url，重启后但似乎没有生效，返回给我的还是0.0.0.0

**Comment by sugar-zero** [comment]
ok，资源问题正常了，但依旧登录不了，点击登录后就会500错误，不管密码对错只要点登录就报500
![image](https://user-images.githubusercontent.com/32754222/89921413-3db47900-dc30-11ea-907c-970fcd368c1d.png)

**Comment by LQBing** [comment]
> ok，资源问题正常了，但依旧登录不了，点击登录后就会500错误，不管密码对错只要点登录就报500
> ![image](https://user-images.githubusercontent.com/32754222/89921413-3db47900-dc30-11ea-907c-970fcd368c1d.png)

500有详细错误信息吗？response和preview里面的内容。
另外 你是本机运行本机访问吗？127.0.0.1:7890

**Comment by sugar-zero** [comment]
> > ok，资源问题正常了，但依旧登录不了，点击登录后就会500错误，不管密码对错只要点登录就报500
> > ![图片](https://user-images.githubusercontent.com/32754222/89921413-3db47900-dc30-11ea-907c-970fcd368c1d.png)
> 
> 500有详细错误信息吗？响应和预览里面的内容。另外
> 你是本机运行本机访问吗？127.0.0.1：7890

![image](https://user-images.githubusercontent.com/32754222/89922046-1a3dfe00-dc31-11ea-8828-0534299905d4.png)
![image](https://user-images.githubusercontent.com/32754222/89922066-1f02b200-dc31-11ea-8ced-fbf173af2e88.png)
都是一样的东西
不是本地访问，在服务器上，通过反代理访问的

**Comment by LQBing** [comment]
缝合怪的那个命令行有什么错误信息吗？debug不打开看不出来是什么错误啊

**Comment by LQBing** [comment]
> > > ok，资源问题正常了，但依旧登录不了，点击登录后就会500错误，不管密码对错只要点登录就报500
> > > ![图片](https://user-images.githubusercontent.com/32754222/89921413-3db47900-dc30-11ea-907c-970fcd368c1d.png)
> > 
> > 
> > 500有详细错误信息吗？响应和预览里面的内容。另外
> > 你是本机运行本机访问吗？127.0.0.1：7890
> 
> ![image](https://user-images.githubusercontent.com/32754222/89922046-1a3dfe00-dc31-11ea-8828-0534299905d4.png)
> ![image](https://user-images.githubusercontent.com/32754222/89922066-1f02b200-dc31-11ea-8ced-fbf173af2e88.png)
> 都是一样的东西
> 不是本地访问，在服务器上，通过反代理访问的

缝合怪的那个命令行有什么错误信息吗？debug不打开看不出来是什么错误啊。

**Comment by sugar-zero** [comment]
在log中翻到了报错
 File "C:\Users\Administrator\Desktop\xcwBot\HoshinoBot\hoshino\modules\bot_manager_web\view.py", line 48, in login
    if input_psd == hoshino.config.bot_manager_web.PASSWORD:
AttributeError: module 'hoshino.config' has no attribute 'bot_manager_web'

**Comment by sugar-zero** [comment]
> 在
> 文件中翻到了报错文件“ C：\ Users \ Administrator \ Desktop \ xcwBot \ HoshinoBot \ hoshino \ modules \ bot_manager_web \ view.py”中，
> 如果input_psd == hoshino.config.bot_manager_web.PASSWORD ，则登录：
> AttributeError ：模块'hoshino.config'没有属性'bot_manager_web'

![image](https://user-images.githubusercontent.com/32754222/89922851-368e6a80-dc32-11ea-9a9d-e7e6b69552cc.png)
模块是加了的

**Comment by LQBing** [comment]
> > 在
> > 文件中翻到了报错文件“ C：\ Users \ Administrator \ Desktop \ xcwBot \ HoshinoBot \ hoshino \ modules \ bot_manager_web \ view.py”中，
> > 如果input_psd == hoshino.config.bot_manager_web.PASSWORD ，则登录：
> > AttributeError ：模块'hoshino.config'没有属性'bot_manager_web'
> 
> ![image](https://user-images.githubusercontent.com/32754222/89922851-368e6a80-dc32-11ea-9a9d-e7e6b69552cc.png)
> 模块是加了的

是我没删干净。。。
之前是依照hoshino的方式配置放在‘hoshino.config’目录下，后来好像很多人不喜欢，就挪进modules代码里了。这个是漏了，我再检查一遍看看还有么有漏的，没有我就更新一下。

**Comment by sugar-zero** [comment]
> > > 在
> > > 文件中翻到了报错文件“ C：\ Users \ Administrator \ Desktop \ xcwBot \ HoshinoBot \ hoshino \ modules \ bot_manager_web \ view.py”中，
> > > 如果input_psd == hoshino.config.bot_manager_web.PASSWORD ，则登录：
> > > AttributeError ：模块'hoshino.config'没有属性'bot_manager_web'
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/32754222/89922851-368e6a80-dc32-11ea-9a9d-e7e6b69552cc.png)
> > 模块是加了的
> 
> 是我没删干净。。。
> 之前是依照hoshino的方式配置放在‘hoshino.config’目录下，后来好像很多人不喜欢，就挪进modules代码里了。这个是漏了，我再检查一遍看看还有么有漏的，没有我就更新一下。

好的

**Comment by LQBing** [comment]
> > > > 在
> > > > 文件中翻到了报错文件“ C：\ Users \ Administrator \ Desktop \ xcwBot \ HoshinoBot \ hoshino \ modules \ bot_manager_web \ view.py”中，
> > > > 如果input_psd == hoshino.config.bot_manager_web.PASSWORD ，则登录：
> > > > AttributeError ：模块'hoshino.config'没有属性'bot_manager_web'
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/32754222/89922851-368e6a80-dc32-11ea-9a9d-e7e6b69552cc.png)
> > > 模块是加了的
> > 
> > 
> > 是我没删干净。。。
> > 之前是依照hoshino的方式配置放在‘hoshino.config’目录下，后来好像很多人不喜欢，就挪进modules代码里了。这个是漏了，我再检查一遍看看还有么有漏的，没有我就更新一下。
> 
> 好的

更新了，就一个文件 view.py

**Comment by sugar-zero** [comment]
修好了，感谢大佬~

**Comment by LQBing** [comment]
> 修好了，感谢大佬~

:)
没有其他问题我关掉这个issue了哦
